version: '3'

services:
    app:
        build: .
        entrypoint: .docker/entrypoint.sh
        container_name: api-app-mobile-tcc
        ports:
            - '3000:3000'
        volumes:
            - .:/home/node/app
        depends_on:
            - db
            - redis

    db:
        image: bitnami/postgresql:latest
        container_name: api-app-mobile-db-tcc
        restart: always
        tty: true
        ports:
            - '5423:5432'
        volumes:
            - .docker/dbdata:/bitnami/postgresql
        environment:
            - POSTGRESQL_PASSWORD=0d22391e8c6125e8f2e3361dcad043fc
            - POSTGRESQL_DATABASE=apitcc

    redis:
        image: 'bitnami/redis:latest'
        container_name: api-app-mobile-redis-tcc
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
