version: '3'

services:
    app:
        build: .
        entrypoint: .docker/entrypoint.sh
        container_name: api-app-mobile-tcc
        ports:
            - '3000:3000'
        volumes:
            - .:/home/node/app
        depends_on:
            - db
            - redis

    db:
        build: .docker/postgres
        container_name: api-app-mobile-db-tcc
        restart: always
        tty: true
        ports:
            - '5432:5432'
        volumes:
            - .docker/dbdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=app

    redis:
        image: 'bitnami/redis:latest'
        container_name: api-app-mobile-redis-tcc
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
